### ISSUE TITLE
Support newer versions of C++/WinRT

### ISSUE THREAD

**Issue by robmikh** [robmikh/robmikh.common#2]
Newer versions of C++/WinRT have changed the way coroutine support is handled. I've already had to put together at least one workaround for [Win32CaptureSample](https://github.com/robmikh/Win32CaptureSample/commit/fc758e343ca886795b05af5003d9a3bb85ff4da2).

The other header that needs to be fixed is imaging, since it (sloppily) uses std::future to return a winrt::com_ptr. Replacing this will also solve the issue of burning a thread for each of those calls. Unfortunately, IAsyncOperation only works for WinRT interfaces, and not for interfaces that only inherit from IUnknown.

Related: https://github.com/robmikh/Win32CaptureSample/issues/67

**Comment by jaimecbernardo** [comment]
Hi, I've opened a new issue in CppWinRT: https://github.com/microsoft/cppwinrt/issues/1391
For the meantime, we'll try using the suggested workaround in PowerToys.

**Comment by robmikh** [comment]
This should now be fixed with v0.0.23
